language: python

python:
  - "3.7"

os: linux
sudo: required
dist: bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnat zlib1g-dev

before_script:
  - git clone https://github.com/tgingold/ghdl.git ghdl
  - git clone https://github.com/cocotb/cocotb.git
  - cd ghdl
  - make
  - sudo make install
  - cd ../cocotb
  - pip install -e .
  - cd ..

script:
  - cd cocotb/tests/test_cases/test_configuration
  - export SIM=ghdl
  - make test